# GoReleaser configuration for lofitui-go
# Builds for all platforms and auto-publishes to homebrew-tap

version: 2

before:
  hooks:
    - go test ./...
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: lofitui
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - name: lofitui
    repository:
      owner: willyv3
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: https://github.com/willyv3/lofitui-go
    description: "Terminal UI for playing YouTube lofi streams with mpv"
    license: MIT
    directory: Formula
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com
    commit_msg_template: "Brew formula update for lofitui version {{ .Tag }}"

    # Runtime dependencies
    dependencies:
      - name: mpv
      - name: yt-dlp

    # Installation caveats
    caveats: |
      ░█░░░█▀█░█▀▀░▀█▀░▀█▀░█░█░▀█▀
      ░█░░░█░█░█▀▀░░█░░░█░░█░█░░█░
      ░▀▀▀░▀▀▀░▀░░░▀▀▀░░▀░░▀▀▀░▀▀▀

      Terminal UI for lofi streams!

      Quick start:
        lofitui

      Key bindings:
        m - Manage presets
        c - Custom URL
        q - Quit

      Config location:
        ~/.config/lofitui/config.json

      Dependencies installed:
        • mpv (video player)
        • yt-dlp (stream extractor)

    test: |
      system "#{bin}/lofitui", "--version"
